### ISSUE TITLE
 question: could you point out the differences to other hcloud gem?

### ISSUE THREAD

**Issue by whysthatso** [floriandejonckheere/hcloud#13]
it might make sense to delineate it from:
https://github.com/tonobo/hcloud-ruby

**Comment by floriandejonckheere** [comment]
Hi, I originally extracted this library from one of [my other projects](https://github.com/floriandejonckheere/kozo). I was using https://github.com/tonobo/hcloud-ruby, but for reasons I don't recall, the gem did not do everything I wanted it to do, or the paradigm didn't exactly fit my code. Don't remember exactly. It was also a programming exercise for me.

Looking at the two libraries now, the differences I spot are:
- Support for labels
- Support for Pricing API
- Scheduled integration tests
- Missing some actions (mostly for server and load balancer resources)
