### ISSUE TITLE
Missing attributes

### ISSUE THREAD

**Issue by Tashows** [floriandejonckheere/hcloud#22]
Maybe setting attributes to resources should have a failsafe/fallback to log warnings instead. Right now this is very susceptible to break whenever there is any change on the resources' attributes via the hetzner team. Being always up to date is not going to be maintainable in the long run.

I will try to look into it a bit, but this might be very easy for you to do already. Any thoughts?

**Comment by floriandejonckheere** [comment]
I added setting attributes on the fly in [v1.5.4](https://github.com/floriandejonckheere/hcloud/releases/tag/v1.5.4). It logs a warning when it happens for the first time as well.
