### ISSUE TITLE
Unknown attribute HCloud::ServerType#deprecation

### ISSUE THREAD

**Issue by quaasi** [floriandejonckheere/hcloud#23]
I just tried out this gem and ran directly into this issue. It's a complete new project I started so there should be no side effects.

* Ruby 3.1.4. 
* hetznercloud gem 1.5.4

Steps to reproduce:
```ruby
require "hcloud"
client = HCloud::Client.new(access_token: "...")
HCloud::Client.connection = client
HCloud::Server.last
```
Then I got the error message with the very convenient  link to create a new issue ;)

**Comment by floriandejonckheere** [comment]
Hey, thanks for reporting this. Sometimes Hetzner changes their API, and to prevent this gem from breaking a warning is printed. The attribute should still be accessible on the resource, though just the plain data.

I'll release a new version of the gem soon, after I add this attribute and fix a couple more bugs I found.
